message.service.urls=http://localhost:1238/message_service,http://localhost:1239/message_service
logging.service.urls=http://localhost:1240/logging_service,http://localhost:1241/logging_service,http://localhost:1242/logging_service
server.port=1232
