message.service.url=http://localhost:1238/message_service
logging.service.urls=http://localhost:1236/logging_service,http://localhost:1237/logging_service,http://localhost:1239/logging_service
server.port=1240
